version: "3.9"

services:
  app:
    build: .
    container_name: express_app
    restart: unless-stopped
    environment:
      - MONGO_URI=mongodb://mongo:27017/codeless
      - NODE_ENV=production
      - PORT=3000
    ports:
      - "3000:3000"
    depends_on:
      - mongo

  mongo:
    image: mongo:7.0
    container_name: mongo
    restart: unless-stopped
    environment:
      - MONGO_INITDB_DATABASE=codeless
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
